var myData = [
    {
        provinceName: "安徽",
        belong  : "华北地区",
        code    : 5785,
        spel     : "A",
        citys   : [
            {name: "合肥", pingyin: "hefei"},
            {name: "安庆", pingyin: "anqing"},
            {name: "蚌埠", pingyin: "bengbeng"},
            {name: "亳州", pingyin: "haozhou"},
            {name: "巢湖", pingyin: "chaohu"},
            {name: "池州", pingyin: "chizhou"},
            {name: "滁州", pingyin: "chuzhou"},
            {name: "阜阳", pingyin: "fuyang"},
            {name: "淮北", pingyin: "huaibei"},
            {name: "淮南", pingyin: "huainan"},
            {name: "黄山", pingyin: "huangshan"},
            {name: "六安", pingyin: "liuan"},
            {name: "马鞍山", pingyin: "maanshan"},
            {name: "宿州", pingyin: "suzhou"},
            {name: "铜陵", pingyin: "tongling"},
            {name: "芜湖", pingyin: "wuhu"},
            {name: "宣城", pingyin: "xuancheng"}
        ]
    },
    {
        provinceName: "福建",
        belong  : "",
        code    : 5785,
        spel     : "F",
        citys   : [
            {name: "福州", pingyin: "fuzhou"},
            {name: "龙岩", pingyin: "longyan"},
            {name: "南平", pingyin: "nanping"},
            {name: "宁德", pingyin: "ningde"},
            {name: "莆田", pingyin: "putian"},
            {name: "泉州", pingyin: "quanzhou"},
            {name: "三明", pingyin: "sanming"},
            {name: "厦门", pingyin: "xiamen"},
            {name: "漳州", pingyin: "zhangzhou"}
        ]
    },
    {
        provinceName: "广东",
        belong  : "",
        code    : 5776,
        spel     : "G",
        citys   : [
            {name: "广州", pingyin: "guangzhou"},
            {name: "潮州", pingyin: "chaozhou"},
            {name: "东莞", pingyin: "dongguan"},
            {name: "佛山", pingyin: "foshan"},
            {name: "河源", pingyin: "heyuan"},
            {name: "惠州", pingyin: "huizhou"},
            {name: "江门", pingyin: "jiangmen"},
            {name: "揭阳", pingyin: "jieyang"},
            {name: "茂名", pingyin: "maoming"},
            {name: "梅州", pingyin: "meizhou"},
            {name: "清远", pingyin: "qingyuan"},
            {name: "汕头", pingyin: "shantou"},
            {name: "汕尾", pingyin: "shanwei"},
            {name: "韶关", pingyin: "shaoguan"},
            {name: "深圳", pingyin: "shenzhen"},
            {name: "阳江", pingyin: "yangjiang"},
            {name: "云浮", pingyin: "yunfu"},
            {name: "湛江", pingyin: "zhanjiang"},
            {name: "肇庆", pingyin: "zhaoqing"},
            {name: "中山", pingyin: "zhongshan"},
            {name: "珠海", pingyin: "zhuhai"}
        ]
    },
    {
        provinceName: "广西",
        belong  : "",
        code    : 5786,
        spel     : "G",
        citys   : [
            {name: "南宁", pingyin: "nanning"},
            {name: "百色", pingyin: "baise"},
            {name: "北海", pingyin: "beihai"},
            {name: "崇左", pingyin: "congzuo"},
            {name: "防城港", pingyin: "fangchenggang"},
            {name: "桂林", pingyin: "guilin"},
            {name: "贵港", pingyin: "guiyang"},
            {name: "河池", pingyin: "hechi"},
            {name: "贺州", pingyin: "hezhou"},
            {name: "来宾", pingyin: "laibin"},
            {name: "柳州", pingyin: "louzhou"},
            {name: "钦州", pingyin: "qinzhou"},
            {name: "梧州", pingyin: "wuzhou"},
            {name: "玉林", pingyin: "yulin"}
        ]
    },
    {
        provinceName: "贵州",
        belong  : "",
        code    : 5793,
        spel     : "G",
        citys   : [
            {name: "贵阳", pingyin: "guiyang"},
            {name: "安顺", pingyin: "anshun"},
            {name: "毕节地区", pingyin: "bijiediqu"},
            {name: "六盘水", pingyin: "liupanshui"},
            {name: "铜仁地区", pingyin: "tongrendiqu"},
            {name: "遵义", pingyin: "zunyi"},
            {name: "黔西南州", pingyin: "qianxinanzhou"},
            {name: "黔东南州", pingyin: "qiandongnanzhou"},
            {name: "黔南州", pingyin: "qiannanzhou"}
        ]
    },
    {
        provinceName: "甘肃",
        belong  : "",
        code    : 5775,
        spel     : "G",
        citys   : [
            {name: "兰州", pingyin: "lanzhou"},
            {name: "白银", pingyin: "banyin"},
            {name: "定西", pingyin: "dingxi"},
            {name: "甘南州", pingyin: "gannanzhou"},
            {name: "嘉峪关", pingyin: "jiayuguan"},
            {name: "金昌", pingyin: "jinchang"},
            {name: "酒泉", pingyin: "jiuquan"},
            {name: "临夏州", pingyin: "linxiazhou"},
            {name: "陇南", pingyin: "longnan"},
            {name: "平凉", pingyin: "pinliang"},
            {name: "庆阳", pingyin: "qingyang"},
            {name: "天水", pingyin: "tianshui"},
            {name: "武威", pingyin: "wuwei"},
            {name: "张掖", pingyin: "zhangye"}
        ]
    },
    {
        provinceName: "海南",
        code    : 5790,
        spel     : "H",
        citys   : [
            {name: "海口", pingyin: "haikou"},
            {name: "白沙", pingyin: "baisha"},
            {name: "保亭", pingyin: "baoting"},
            {name: "昌江", pingyin: "changjiang"},
            {name: "儋州", pingyin: "zhanzhou"},
            {name: "澄迈", pingyin: "chengmai"},
            {name: "东方", pingyin: "dongfang"},
            {name: "定安", pingyin: "dingan"},
            {name: "琼海", pingyin: "qionghai"},
            {name: "琼中", pingyin: "qiongzhong"},
            {name: "乐东", pingyin: "ledong"},
            {name: "陵水", pingyin: "lingshui"},
            {name: "三亚", pingyin: "sanya"},
            {name: "屯昌", pingyin: "tunchang"},
            {name: "万宁", pingyin: "wanning"},
            {name: "文昌", pingyin: "wenchang"},
            {name: "五指山", pingyin: "wuzhishan"}
        ]
    },
    {
        provinceName: "河南",
        code    : 5799,
        spel     : "H",
        citys   : [
            {name: "郑州", pingyin: "zhengzhou"},
            {name: "安阳", pingyin: "anyang"},
            {name: "鹤壁", pingyin: "hebi"},
            {name: "焦作", pingyin: "jiaozuo"},
            {name: "开封", pingyin: "kaifeng"},
            {name: "洛阳", pingyin: "luoyang"},
            {name: "漯河", pingyin: "luohe"},
            {name: "南阳", pingyin: "nanyang"},
            {name: "平顶山", pingyin: "pingdingshan"},
            {name: "濮阳", pingyin: "puyang"},
            {name: "三门峡", pingyin: "sanmenxia"},
            {name: "商丘", pingyin: "shangqiu"},
            {name: "新乡", pingyin: "xinxiang"},
            {name: "信阳", pingyin: "xinyang"},
            {name: "许昌", pingyin: "xuchang"},
            {name: "周口", pingyin: "zhoukou"},
            {name: "驻马店", pingyin: "zhumadian"}
        ]
    }
]
